local modpath = minetest.get_modpath("sbz_chem")

dofile(modpath .. "/fluids.lua")
dofile(modpath .. "/elements.lua")
dofile(modpath .. "/radiation.lua")
dofile(modpath .. "/centrifuge.lua")
dofile(modpath .. "/crusher.lua")
dofile(modpath .. "/alloy_furnace.lua")
dofile(modpath .. "/hpef.lua")
dofile(modpath .. "/compressor.lua")
dofile(modpath .. "/crystal_grower.lua")
dofile(modpath .. "/reactor.lua")
dofile(modpath .. "/pebble_enhancer.lua")
dofile(modpath .. "/decay_chains.lua")
dofile(modpath .. "/decay_accel.lua")
dofile(modpath .. "/engraver.lua")
dofile(modpath .. "/melter_cooler.lua")
