-- https://github.com/mt-mods/digistuff/blob/reworkGPU/gpu-font.lua
-- license: LGPLv3 or later
-- i feel like cheapie went slightly insane here while making this... because.... what....
local T = true
local F = false

local default_font = {
    [32] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [33] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, F, F, F, F, },
        { T, F, F, F, F, },
        { T, F, F, F, F, },
        { T, F, F, F, F, },
        { T, F, F, F, F, },
        { F, F, F, F, F, },
        { T, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [34] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, F, T, F, F, },
        { T, F, T, F, F, },
        { T, F, T, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [35] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, F, T, F, },
        { F, T, F, T, F, },
        { T, T, T, T, T, },
        { F, T, F, T, F, },
        { F, T, F, T, F, },
        { T, T, T, T, T, },
        { F, T, F, T, F, },
        { F, T, F, T, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [36] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, T, F, F, },
        { F, T, T, T, F, },
        { T, F, F, F, F, },
        { F, T, T, F, F, },
        { F, F, F, T, F, },
        { T, F, F, T, F, },
        { F, T, T, F, F, },
        { F, F, T, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [37] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, T, F, F, },
        { T, F, T, F, F, },
        { T, T, F, F, T, },
        { F, F, T, T, F, },
        { F, T, F, T, T, },
        { T, F, F, T, F, },
        { F, F, F, T, T, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [38] = {
        { F, T, T, F, F, },
        { T, F, F, F, F, },
        { F, T, T, F, T, },
        { T, F, F, T, F, },
        { F, T, T, F, T, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [39] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, F, F, F, F, },
        { T, F, F, F, F, },
        { T, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [40] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, T, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { T, F, F, F, F, },
        { T, F, F, F, F, },
        { T, F, F, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { F, F, T, F, F, },
        { F, F, F, F, F, },
    },
    [41] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, F, F, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { F, F, T, F, F, },
        { F, F, T, F, F, },
        { F, F, T, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { T, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [42] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, T, F, F, },
        { T, T, F, T, T, },
        { F, F, T, F, F, },
        { F, T, F, T, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [43] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, T, F, F, },
        { F, F, T, F, F, },
        { T, T, T, T, T, },
        { F, F, T, F, F, },
        { F, F, T, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [44] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { T, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [45] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, T, T, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [46] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, F, F, F, F, },
        { T, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [47] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, T, },
        { F, F, F, T, F, },
        { F, F, F, T, F, },
        { F, F, T, F, F, },
        { F, F, T, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { T, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [48] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, T, F, F, },
        { T, F, F, T, F, },
        { T, F, F, T, F, },
        { T, F, F, T, F, },
        { T, F, F, T, F, },
        { T, F, F, T, F, },
        { F, T, T, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [49] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, T, F, F, },
        { T, T, T, F, F, },
        { F, F, T, F, F, },
        { F, F, T, F, F, },
        { F, F, T, F, F, },
        { F, F, T, F, F, },
        { T, T, T, T, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [50] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, T, F, F, },
        { T, F, F, T, F, },
        { F, F, F, T, F, },
        { F, F, T, F, F, },
        { F, T, F, F, F, },
        { T, F, F, F, F, },
        { T, T, T, T, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [51] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, T, F, F, },
        { T, F, F, T, F, },
        { F, F, F, T, F, },
        { F, T, T, F, F, },
        { F, F, F, T, F, },
        { T, F, F, T, F, },
        { F, T, T, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [52] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, T, F, },
        { F, F, T, T, F, },
        { F, T, F, T, F, },
        { T, F, F, T, F, },
        { T, T, T, T, T, },
        { F, F, F, T, F, },
        { F, F, F, T, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [53] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, T, T, F, },
        { T, F, F, F, F, },
        { T, F, F, F, F, },
        { T, T, T, F, F, },
        { F, F, F, T, F, },
        { F, F, F, T, F, },
        { T, T, T, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [54] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, T, T, F, },
        { T, F, F, F, F, },
        { T, F, F, F, F, },
        { T, T, T, F, F, },
        { T, F, F, T, F, },
        { T, F, F, T, F, },
        { F, T, T, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [55] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, T, T, F, },
        { T, F, F, T, F, },
        { F, F, F, T, F, },
        { F, F, T, F, F, },
        { F, F, T, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [56] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, T, F, F, },
        { T, F, F, T, F, },
        { T, F, F, T, F, },
        { F, T, T, F, F, },
        { T, F, F, T, F, },
        { T, F, F, T, F, },
        { F, T, T, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [57] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, T, F, F, },
        { T, F, F, T, F, },
        { T, F, F, T, F, },
        { F, T, T, T, F, },
        { F, F, F, T, F, },
        { F, F, F, T, F, },
        { T, T, T, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [58] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [59] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { F, F, F, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { T, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [60] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, T, F, F, },
        { F, T, F, F, F, },
        { T, F, F, F, F, },
        { F, T, F, F, F, },
        { F, F, T, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [61] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, T, T, F, },
        { F, F, F, F, F, },
        { T, T, T, T, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [62] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, F, F, F, F, },
        { F, T, F, F, F, },
        { F, F, T, F, F, },
        { F, T, F, F, F, },
        { T, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [63] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, T, F, F, },
        { T, F, F, T, F, },
        { F, F, T, F, F, },
        { F, T, F, F, F, },
        { F, F, F, F, F, },
        { F, T, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [64] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, T, T, T, },
        { F, T, F, F, F, },
        { T, F, F, T, T, },
        { T, F, T, F, T, },
        { T, F, T, F, T, },
        { T, F, F, T, T, },
        { F, T, F, F, F, },
        { F, F, T, T, T, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [65] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, T, T, F, },
        { F, F, T, F, T, },
        { F, T, F, F, T, },
        { F, T, T, T, T, },
        { F, T, F, F, T, },
        { T, T, F, F, T, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [66] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, T, T, F, },
        { F, T, F, F, T, },
        { F, T, T, T, F, },
        { F, T, F, F, T, },
        { F, T, F, F, T, },
        { T, T, T, T, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [67] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, T, F, F, },
        { T, F, F, T, F, },
        { T, F, F, F, F, },
        { T, F, F, F, F, },
        { T, F, F, T, F, },
        { F, T, T, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [68] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, T, T, F, },
        { F, T, F, F, T, },
        { F, T, F, F, T, },
        { F, T, F, F, T, },
        { F, T, F, F, T, },
        { T, T, T, T, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [69] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, T, T, T, },
        { F, T, F, F, T, },
        { F, T, T, T, F, },
        { F, T, F, F, F, },
        { F, T, F, F, T, },
        { T, T, T, T, T, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [70] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, T, T, T, },
        { F, T, F, F, T, },
        { F, T, T, T, F, },
        { F, T, F, T, F, },
        { F, T, F, F, F, },
        { T, T, T, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [71] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, T, F, F, },
        { T, F, F, T, F, },
        { T, F, F, F, F, },
        { T, F, T, T, F, },
        { T, F, F, T, F, },
        { F, T, T, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [72] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, F, F, T, },
        { F, T, F, F, T, },
        { F, T, T, T, T, },
        { F, T, F, F, T, },
        { F, T, F, F, T, },
        { T, T, F, F, T, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [73] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, T, T, T, },
        { F, F, T, F, F, },
        { F, F, T, F, F, },
        { F, F, T, F, F, },
        { F, F, T, F, F, },
        { T, T, T, T, T, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [74] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, T, T, T, },
        { F, F, F, T, F, },
        { F, F, F, T, F, },
        { T, F, F, T, F, },
        { T, F, F, T, F, },
        { F, T, T, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [75] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, F, T, T, },
        { F, T, F, T, F, },
        { F, T, T, F, F, },
        { F, T, F, T, F, },
        { F, T, F, F, T, },
        { T, T, T, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [76] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, T, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, T, },
        { T, T, T, T, T, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [77] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, F, F, F, T, },
        { T, T, F, T, T, },
        { T, F, T, F, T, },
        { T, F, T, F, T, },
        { T, F, F, F, T, },
        { T, T, F, T, T, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [78] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, F, T, T, },
        { F, T, F, F, T, },
        { F, T, T, F, T, },
        { F, T, F, T, T, },
        { F, T, F, F, T, },
        { T, T, F, F, T, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [79] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, T, F, F, },
        { T, F, F, T, F, },
        { T, F, F, T, F, },
        { T, F, F, T, F, },
        { T, F, F, T, F, },
        { F, T, T, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [80] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, T, T, F, },
        { F, T, F, F, T, },
        { F, T, F, F, T, },
        { F, T, T, T, F, },
        { F, T, F, F, F, },
        { T, T, T, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [81] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, T, F, F, },
        { T, F, F, T, F, },
        { T, F, F, T, F, },
        { T, F, F, T, F, },
        { T, F, F, T, F, },
        { F, T, T, F, F, },
        { F, T, T, T, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [82] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, T, T, F, },
        { F, T, F, F, T, },
        { F, T, F, F, T, },
        { F, T, T, T, F, },
        { F, T, F, F, T, },
        { T, T, T, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [83] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, T, T, F, },
        { T, F, F, F, F, },
        { F, T, T, F, F, },
        { F, F, F, T, F, },
        { T, F, F, T, F, },
        { T, T, T, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [84] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, T, T, T, },
        { T, F, T, F, T, },
        { F, F, T, F, F, },
        { F, F, T, F, F, },
        { F, F, T, F, F, },
        { F, T, T, T, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [85] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, F, F, T, },
        { F, T, F, F, T, },
        { F, T, F, F, T, },
        { F, T, F, F, T, },
        { F, T, F, F, T, },
        { F, F, T, T, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [86] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, F, T, T, },
        { T, F, F, F, T, },
        { F, T, F, T, F, },
        { F, T, F, T, F, },
        { F, T, F, T, F, },
        { F, F, T, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [87] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, F, T, T, },
        { T, F, F, F, T, },
        { T, F, T, F, T, },
        { T, F, T, F, T, },
        { F, T, F, T, F, },
        { F, T, F, T, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [88] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, F, T, T, },
        { F, T, F, T, F, },
        { F, F, T, F, F, },
        { F, F, T, F, F, },
        { F, T, F, T, F, },
        { T, T, F, T, T, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [89] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, F, T, T, },
        { T, F, F, F, T, },
        { F, T, F, T, F, },
        { F, F, T, F, F, },
        { F, F, T, F, F, },
        { F, T, T, T, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [90] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, T, T, F, },
        { T, F, F, T, F, },
        { F, F, T, F, F, },
        { F, T, F, F, F, },
        { T, F, F, T, F, },
        { T, T, T, T, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [91] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, F, F, F, },
        { T, F, F, F, F, },
        { T, F, F, F, F, },
        { T, F, F, F, F, },
        { T, F, F, F, F, },
        { T, F, F, F, F, },
        { T, F, F, F, F, },
        { T, F, F, F, F, },
        { T, T, F, F, F, },
        { F, F, F, F, F, },
    },
    [92] = {
        { F, F, F, F, F, },
        { T, F, F, F, F, },
        { T, F, F, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { F, F, T, F, F, },
        { F, F, T, F, F, },
        { F, F, F, T, F, },
        { F, F, F, T, F, },
        { F, F, F, F, T, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [93] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, F, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { T, T, F, F, F, },
        { F, F, F, F, F, },
    },
    [94] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, T, F, F, },
        { F, T, F, T, F, },
        { T, F, F, F, T, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [95] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, T, T, T, },
        { F, F, F, F, F, },
    },
    [96] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, F, F, F, F, },
        { F, T, F, F, F, },
        { F, F, T, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [97] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, T, F, F, },
        { F, F, F, T, F, },
        { F, T, T, T, F, },
        { T, F, F, T, F, },
        { F, T, T, F, T, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [98] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, F, F, F, },
        { F, T, F, F, F, },
        { F, T, T, T, F, },
        { F, T, F, F, T, },
        { F, T, F, F, T, },
        { F, T, F, F, T, },
        { T, T, T, T, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [99] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, T, F, F, },
        { T, F, F, T, F, },
        { T, F, F, F, F, },
        { T, F, F, T, F, },
        { F, T, T, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [100] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, T, T, F, },
        { F, F, F, T, F, },
        { F, T, T, T, F, },
        { T, F, F, T, F, },
        { T, F, F, T, F, },
        { T, F, F, T, F, },
        { F, T, T, F, T, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [101] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, T, F, F, },
        { T, F, F, T, F, },
        { T, T, T, F, F, },
        { T, F, F, T, F, },
        { F, T, T, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [102] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, T, T, F, },
        { F, T, F, F, F, },
        { T, T, T, T, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { T, T, T, T, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [103] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, T, F, T, },
        { T, F, F, T, F, },
        { T, F, F, T, F, },
        { T, F, F, T, F, },
        { F, T, T, T, F, },
        { F, F, F, T, F, },
        { T, T, T, F, F, },
        { F, F, F, F, F, },
    },
    [104] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, F, F, F, },
        { F, T, F, F, F, },
        { F, T, T, T, F, },
        { F, T, F, F, T, },
        { F, T, F, F, T, },
        { F, T, F, F, T, },
        { T, T, T, F, T, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [105] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, T, F, F, },
        { F, F, F, F, F, },
        { F, T, T, F, F, },
        { F, F, T, F, F, },
        { F, F, T, F, F, },
        { F, F, T, F, F, },
        { T, T, T, T, T, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [106] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, T, F, F, },
        { F, F, F, F, F, },
        { T, T, T, F, F, },
        { F, F, T, F, F, },
        { F, F, T, F, F, },
        { F, F, T, F, F, },
        { F, F, T, F, F, },
        { F, F, T, F, F, },
        { T, T, F, F, F, },
        { F, F, F, F, F, },
    },
    [107] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, F, F, F, },
        { F, T, F, F, F, },
        { F, T, F, T, T, },
        { F, T, F, T, F, },
        { F, T, T, F, F, },
        { F, T, F, T, F, },
        { T, T, F, T, T, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [108] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, T, F, F, },
        { F, F, T, F, F, },
        { F, F, T, F, F, },
        { F, F, T, F, F, },
        { F, F, T, F, F, },
        { F, F, T, F, F, },
        { T, T, T, T, T, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [109] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, F, T, F, },
        { T, F, T, F, T, },
        { T, F, T, F, T, },
        { T, F, T, F, T, },
        { T, F, T, F, T, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [110] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, F, T, T, F, },
        { F, T, F, F, T, },
        { F, T, F, F, T, },
        { F, T, F, F, T, },
        { T, T, T, F, T, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [111] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, T, F, F, },
        { T, F, F, T, F, },
        { T, F, F, T, F, },
        { T, F, F, T, F, },
        { F, T, T, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [112] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, F, T, T, F, },
        { F, T, F, F, T, },
        { F, T, F, F, T, },
        { F, T, F, F, T, },
        { F, T, T, T, F, },
        { F, T, F, F, F, },
        { T, T, T, T, F, },
        { F, F, F, F, F, },
    },
    [113] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, T, F, T, },
        { T, F, F, T, F, },
        { T, F, F, T, F, },
        { T, F, F, T, F, },
        { F, T, T, T, F, },
        { F, F, F, T, F, },
        { F, F, T, T, T, },
        { F, F, F, F, F, },
    },
    [114] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, F, T, T, T, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { T, T, T, T, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [115] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, T, T, F, },
        { T, F, F, F, F, },
        { F, T, T, F, F, },
        { F, F, F, T, F, },
        { T, T, T, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [116] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { T, T, T, T, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, T, },
        { F, F, T, T, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [117] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, F, T, T, },
        { F, T, F, F, T, },
        { F, T, F, F, T, },
        { F, T, F, F, T, },
        { F, F, T, T, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [118] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, F, F, T, },
        { F, T, F, F, F, },
        { F, F, T, F, T, },
        { F, F, T, F, T, },
        { F, F, F, T, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [119] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, F, T, F, T, },
        { T, F, T, F, T, },
        { T, F, T, F, T, },
        { F, T, F, T, F, },
        { F, T, F, T, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [120] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, F, T, T, },
        { F, T, F, T, F, },
        { F, F, T, F, F, },
        { F, T, F, T, F, },
        { T, T, F, T, T, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [121] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, F, T, T, },
        { F, T, F, F, T, },
        { F, T, F, F, T, },
        { F, T, F, F, T, },
        { F, F, T, T, F, },
        { F, F, T, F, F, },
        { T, T, F, F, F, },
        { F, F, F, F, F, },
    },
    [122] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, T, T, T, F, },
        { F, F, T, F, F, },
        { F, T, F, F, F, },
        { T, F, F, T, F, },
        { T, T, T, T, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [123] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, T, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { T, F, F, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { F, F, T, F, F, },
        { F, F, F, F, F, },
    },
    [124] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, F, F, F, F, },
        { T, F, F, F, F, },
        { T, F, F, F, F, },
        { T, F, F, F, F, },
        { T, F, F, F, F, },
        { T, F, F, F, F, },
        { T, F, F, F, F, },
        { T, F, F, F, F, },
        { T, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [125] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { T, F, F, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { F, F, T, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { F, T, F, F, F, },
        { T, F, F, F, F, },
        { F, F, F, F, F, },
    },
    [126] = {
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, T, F, T, F, },
        { T, F, T, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
        { F, F, F, F, F, },
    },
}
return {
    ["default"] = default_font
}
