name: test
on: [push, pull_request]
jobs:
  test:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: buckaroobanzay/mtt@main
      with:
        test_mode: game
        mapgen: v7
        additional_config: |
         secure.trusted_mods = mtt, libox
         secure.http_mods = sbz_logic_devices